# Generated by Django 5.1 on 2024-09-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category_orderitems_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_no',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
