# Generated by Django 5.1 on 2024-09-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
