# Generated by Django 5.1 on 2024-09-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
