# Generated by Django 5.1 on 2024-10-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_image_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
